global:
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 60m
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'spongermanalex@gmail.com'
    from: 'djsasha777@mail.ru'
    smarthost: 'smtp.mail.ru:25'
    auth_username: 'djsasha777@mail.ru'
    auth_identity: 'djsasha777@mail.ru'
    auth_password: '1234'