global:
  scrape_interval: 15s 
scrape_configs:

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'prometheus_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "nasos"
    scrape_interval: 5s
    static_configs:
      - targets: ["3.84.62.193:8444"]

  - job_name: "selectel"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.22.48.66:9100"]

  - job_name: "mainLB"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.22.112.207:9100"]