global:
  scrape_interval: 15s 

rule_files:
  - 'prometheus.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
      
scrape_configs:

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'MAIN'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "nasos"
    scrape_interval: 5s
    static_configs:
      - targets: ["3.84.62.193:8444"]

  - job_name: "selectel"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.22.48.66:9100"]

  - job_name: "GNS3"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.215:9100"]

  - job_name: "ubuntuM1"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.22.176.55:9100"]

  - job_name: "kuber-1"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.201:9100"]

  - job_name: "kuber-2"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.202:9100"]

  - job_name: "kuber-3"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.203:9100"]

  - job_name: "kuber-4"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.204:9100"]