- hosts: all
  become: true
  tasks:
   
    - name: Make sure we have all required packages on Ubuntu
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https
        - aptitude
        - btrfs-tools
        - build-essential
        - curl
        - gawk
        - iptables
        - libaio-dev
        - libapparmor-dev
        - libcap-dev
        - libdevmapper-dev
        - libdevmapper1.02.1
        - libglib2.0-dev
        - libgpgme11-dev
        - libjson-glib-dev
        - libprotobuf-dev
        - libseccomp-dev
        - libseccomp2
        - pkg-config
        - protobuf-compiler
      when: ansible_distribution == 'Ubuntu'

