apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: privatehub
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: privat-repo/my-app:1.3
        imagePullPolicy: Always
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
  namespace: privatehub
data:
  .dockerconfigjson: base64-encoded-contents-of-.docker/config.json-file
type: kubernetes.io/dockerconfigjson
