---
# tasks file for metricbeat
- hosts: "metrichost"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  
  tasks:
    - name: Download package
      ansible.builtin.get_url:
        url: "{{ metricbeat_package_url }}"
        dest: /home/metricbeat.deb
        mode: '0777'

    - name: Install deb package for metricbeat
      ansible.builtin.command: dpkg -i /home/metricbeat.deb

    - name: Template metricbeat config
      template:
        src: ./templates/metricbeat.yml.j2
        dest: /etc/metricbeat/metricbeat.yml
      notify:
        - restart metricbeat 

    - name: metricbeat modules enable system
      ansible.builtin.command: metricbeat modules enable system
      register: metr

    - name: metricbeat setup
      ansible.builtin.command: metricbeat setup
      register: metr

    - name: Ensure metricbeat is running (and enable it at boot)
      service: 
        name: metricbeat 
        enabled: yes
      notify:
        - restart metricbeat 
