---
# tasks file for metricbeat
- name: Install deb package for metricbeat
  ansible.builtin.apt:
    deb: ftp://192.168.1.1/AiDisk_a1/repository/metricbeat-8.3.3-amd64.deb
    state: present

- name: Template metricbeat config
  template:
    src: ./templates/metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify:
    - restart metricbeat 

- name: metricbeat modules enable system
  ansible.builtin.command: metricbeat modules enable system
  become: yes
  #become_user: root
  register: metr

- name: metricbeat setup
  ansible.builtin.command: metricbeat setup
  become: yes
  #become_user: root
  register: metr

- name: Ensure metricbeat is running (and enable it at boot)
  service: 
    name: metricbeat 
    enabled: yes
  notify:
    - restart metricbeat 
