---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my_local_pv
  labels:
    type: local
    app: mypv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mypv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my_local_pvc
  labels:
    app: mypv
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi