apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share 
  labels:
    storage: nfs 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.1
    path: /media/AiDisk_a1/myshare
