apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share 
  labels:
    storage: nfs 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.1
    path: /media/AiDisk_a1/myshare

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-share
labels:
  type: nfs
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi